# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'style.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *
from main_video import *


# define the countdown func.


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Attendance Web Camera")
        MainWindow.setWindowIcon(QIcon("ico.ico"))
        MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)
        MainWindow.resize(405, 309)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(343, 5, 61, 21))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label.setGeometry(QtCore.QRect(120, 10, 271, 71))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 63 15pt \"Open Sans Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(15, 270, 80, 30))
        self.label_1.setObjectName("quitBtn")
        self.label_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 8pt \"Open Sans Semibold\";")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 107, 81, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 8pt \"Open Sans Semibold\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 153, 91, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 8pt \"Open Sans Semibold\";")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(106, 104, 261, 22))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(105, 151, 261, 22))
        self.comboBox_2.setStyleSheet("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(15, 270, 80, 30))
        self.pushButton.setStyleSheet("background-color: rgb(23,117,195);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        # adding list of items to combo box
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 196, 80, 30))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 8pt \"Open Sans Semibold\";")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(207, 270, 80, 30))
        self.pushButton_2.setStyleSheet("background-color: rgb(23,117,195);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 270, 80, 30))
        self.pushButton_3.setStyleSheet("background-color: rgb(23,117,195);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 91, 87))
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("AJOU.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 270, 80, 30))
        self.pushButton_4.setStyleSheet("background-color: rgb(23,117,195);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Attendance Web Camera"))
        self.label.setText(_translate("MainWindow", "Attendance Web Camera"))
        self.lcdNumber.setWindowTitle(_translate("MainWindow", "Form"))
        self.label_1.setText(_translate("MainWindow", "Xsasad"))
        self.label_2.setText(_translate("MainWindow", "Choose course"))
        self.label_3.setText(_translate("MainWindow", "Choose facultate"))
        self.comboBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1-course"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2-course"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Electrical and Computer Engineering"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Architecture"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Civil"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.label_4.setText(_translate("MainWindow", "Choose group"))
        self.pushButton_2.setText(_translate("MainWindow", "Save"))
        self.pushButton_3.setText(_translate("MainWindow", "Exit"))
        self.pushButton_4.setText(_translate("MainWindow", "Create"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
